language: node_js
node_js:
  - "5"

git:
  depth: 3

before_script:
  - "npm install -g gulp"
script: "gulp build-master"

# Deploy new database, only if this is on the master branch.
# Note that FIREBASE_TOKEN is set in Travis configs and is automatically used.
after_success: |
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    npm install -g firebase-tools
    firebase deploy --only rules
    firebase database:set / ./build/pathminder.json
  else
    echo "This will not deploy!"
  fi
